version: "3"

services:
  couchpotato:
    image: linuxserver/couchpotato
    ports:
      - "5050:5050"
    volumes:
      - ./couchpotato/config:/config
      - ./transmission/autoadd:/downloads
      - ./couchpotato/movies:/movies
    environment:
      - PGID=$GID
      - PUID=$UID
    depends_on:
      - transmission

  flood:
    image: jesec/flood
    environment:
      - PGID=$GID
      - PUID=$UID
      - TZ=Europe/London
    volumes:
      - ./flood/config:$HOME/.local/share/flood
    ports:
      - 4200:3000

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PGID=$GID
      - PUID=$UID
      - TZ=Europe/London
      - TRANSMISSION_RPC_USERNAME=RPC_USERNAME # change it
      - TRANSMISSION_RPC_PASSWORD=RPC_PASSWORD
    volumes:
      - ./transmission/downloads:/downloads
      - ./transmission/config:/config
      - ./transmission/autoadd:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  plex:
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - PLEX_UID=$UID
      - PLEX_GID=$GID
    network_mode: host
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./transmission/downloads/done:/data

  jellyfin:
    image: jellyfin/jellyfin:latest
    network_mode: host
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./transmission/downloads/done:/media/movies
